import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import DefaultHeader from "@/components/common/header";
import { cn } from "@/lib/utils";
import DefaultFooter from "@/components/common/footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "../../../auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthenticatedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <div className="tw-min-h-screen tw-flex tw-flex-col">
            <div className="tw-px-4 tw-pt-4">
              <DefaultHeader />
            </div>
            <main className="tw-my-4 tw-flex-grow tw-flex tw-flex-col">{children}</main>
            <DefaultFooter />
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
