import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import DefaultHeader from "@/components/common/header";
import { cn } from "@/lib/utils";
import DefaultFooter from "@/components/common/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthenticatedLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className.concat(
          " tw-min-h-screen tw-pt-4 tw-flex tw-flex-col"
        )}
      >
        <DefaultHeader />
        <main className="tw-mt-8 tw-flex-grow">{children}</main>
        <DefaultFooter />
      </body>
    </html>
  );
}
