import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.scss";
import Header from "@/components/common/layout/header";
import SidebarMenu from "@/components/common/layout/sidebar-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="tw-flex tw-min-h-screen">
          <SidebarMenu />
          <div className="tw-flex-grow tw-p-8">
            <Header />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
